// Generated by scripts/generate-ffi.py from abi/ffi-api.toml. Do not edit.
pub const ABI_MAJOR: u32 = 1;
pub const ABI_MINOR: u32 = 3;
pub const BUILD_INFO_FORMAT: u32 = 1;
pub const MAX_BUILD_INFO_BYTES: usize = 1024;
pub const MAX_LIVE_BUFFERS: usize = 4096;
pub const MAX_LIVE_GAMES: usize = 64;
pub const MAX_LIVE_DOCUMENT_RESTORES: usize = 2;
pub const MAX_INPUT_BYTES: usize = 65536;
pub const MAX_OWNED_BUFFER_BYTES: usize = 65536;
pub const MAX_OWNED_BUFFER_TOTAL_BYTES: usize = 4194304;
pub const OWNERSHIP_TOKEN_BITS: u32 = 64;
pub const ABI_SOURCE_SHA256: &str =
    "3b5b2828f2306339034bd825b18481b09f3c7332c34e0ce00f1a5b0cf4ee0836";
pub const DETERMINISTIC_FEATURES: &str = "deterministic-ffi-v1";
pub const BUILD_INFO: &str = concat!(
    "product=NativeXiangqi;crate=xiangqi-ffi;crate_version=0.1.0;",
    "abi=1.3;build_info_format=1;",
    "ownership_token_bits=64;",
    "max_live_games=64;max_live_document_restores=2;",
    "max_input_bytes=65536;",
    "features=deterministic-ffi-v1;",
    "abi_source_sha256=3b5b2828f2306339034bd825b18481b09f3c7332c34e0ce00f1a5b0cf4ee0836",
);
pub const STATUS_OK: u32 = 0;
pub const STATUS_INVALID_ARGUMENT: u32 = 1;
pub const STATUS_ABI_MAJOR_MISMATCH: u32 = 2;
pub const STATUS_ABI_MINOR_MISMATCH: u32 = 3;
pub const STATUS_OUTPUT_NOT_EMPTY: u32 = 4;
pub const STATUS_ALLOCATION_FAILED: u32 = 5;
pub const STATUS_RESOURCE_LIMIT: u32 = 6;
pub const STATUS_INVALID_OWNED_BUFFER: u32 = 7;
pub const STATUS_INTERNAL_ERROR: u32 = 8;
pub const STATUS_INVALID_HANDLE: u32 = 9;
pub const STATUS_INVALID_SQUARE: u32 = 10;
pub const STATUS_PARSE_ERROR: u32 = 11;
pub const STATUS_ILLEGAL_MOVE: u32 = 12;
pub const STATUS_NO_UNDO: u32 = 13;
pub const STATUS_NO_REDO: u32 = 14;
pub const STATUS_INVALID_NODE: u32 = 15;
pub const STATUS_GAME_OVER: u32 = 16;
pub const STATUS_INPUT_TOO_LARGE: u32 = 17;
pub const STATUS_INVALID_RESERVED: u32 = 18;
pub const STATUS_HISTORY_LIMIT: u32 = 19;
pub const STATUS_NODE_LIMIT: u32 = 20;
pub const STATUS_COUNTER_LIMIT: u32 = 21;
pub const CAPABILITY_ABI_INFO: u64 = 1;
pub const CAPABILITY_BUILD_INFO: u64 = 2;
pub const CAPABILITY_OWNED_BUFFERS: u64 = 4;
pub const CAPABILITY_GAME_HANDLES: u64 = 8;
pub const CAPABILITY_BATCH_RULES: u64 = 16;
pub const CAPABILITY_FEN_UCCI: u64 = 32;
pub const CAPABILITY_BASE_HISTORY: u64 = 64;
pub const CAPABILITY_DOCUMENT_TREE: u64 = 128;
pub const CAPABILITY_DOCUMENT_RESTORE: u64 = 256;
