// Generated by scripts/generate-ffi.py from abi/ffi-api.toml. Do not edit.
enum GeneratedFFIABI {
  static let major: UInt32 = 1
  static let minimumMinor: UInt32 = 0
  static let buildInfoFormat: UInt32 = 1
  static let maximumBuildInfoBytes = 1024
  static let sourceSHA256 = "a436cf367554db0b9052bc79c0408ab2119cbce4308ac7e261818e7ad3e0a296"
  static let capabilityAbiInfo: UInt64 = 1
  static let capabilityBuildInfo: UInt64 = 2
  static let capabilityOwnedBuffers: UInt64 = 4
  static let statusOk: UInt32 = 0
  static let statusInvalidArgument: UInt32 = 1
  static let statusAbiMajorMismatch: UInt32 = 2
  static let statusAbiMinorMismatch: UInt32 = 3
  static let statusOutputNotEmpty: UInt32 = 4
  static let statusAllocationFailed: UInt32 = 5
  static let statusResourceLimit: UInt32 = 6
  static let statusInvalidOwnedBuffer: UInt32 = 7
  static let statusInternalError: UInt32 = 8
}
